// api.js
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Create the API instance
export const api = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:5000' }),
  endpoints: (builder) => ({
    addBook: builder.mutation({
      query: (book) => ({
        url: '/books',
        method: 'POST',
        body: book,
      }),
    }),

    getBooks: builder.query({
      query: () => '/books',
    }),




  }),
});

// Export the hooks generated by RTK Query
export const { useAddBookMutation, useGetBooksQuery } = api;
